version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: kuryecini-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: kuryecini
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backend/setup_indexes.py:/docker-entrypoint-initdb.d/setup_indexes.py:ro
    networks:
      - kuryecini-network

  # Redis for Caching (Optional)
  redis:
    image: redis:7.2-alpine
    container_name: kuryecini-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - kuryecini-network

  # Backend API
  backend:
    build: .
    container_name: kuryecini-backend
    restart: unless-stopped
    environment:
      # Database
      MONGO_URL: mongodb://admin:password123@mongodb:27017/kuryecini?authSource=admin
      
      # JWT Settings
      JWT_SECRET: ${JWT_SECRET:-Kuryecini!SecretKey2025_ChangeInProduction}
      JWT_ALGORITHM: HS256
      JWT_EXPIRATION_HOURS: 24
      
      # Platform Settings
      NEARBY_RADIUS_M: 5000
      COURIER_RATE_PER_PACKAGE: 20
      BUSINESS_COMMISSION_PCT: 5
      COURIER_UPDATE_SEC: 5
      COURIER_TIMEOUT_SEC: 10
      
      # Email & Notifications
      EMAIL_FROM: no-reply@kuryecini.com
      EMAIL_PROVIDER: console
      
      # CORS
      CORS_ORIGINS: http://localhost:3000,http://localhost:5173,https://kuryecini.com
      
      # Environment
      ENVIRONMENT: ${ENVIRONMENT:-development}
      APP_VERSION: ${APP_VERSION:-1.0.0}
      
      # Sentry (Optional)
      SENTRY_DSN: ${SENTRY_DSN:-}
      
      # External Services (Optional)
      OSRM_URL: ${OSRM_URL:-}
      
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
    volumes:
      - uploads_data:/app/backend/uploads
    networks:
      - kuryecini-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:
    driver: local
  uploads_data:
    driver: local

networks:
  kuryecini-network:
    driver: bridge